# Data preprocessing for categorical features

In this notebook, I will experiment with encoding categorical features before implementing the preprocessing logic as a reusable function in `src`.

In [8]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

from telco_churn.config import CATEGORICAL_COLUMNS
from telco_churn.paths import TELCO_CUSTOMERS_TRAIN_PATH

## Prepare categorical features for encoding

In [9]:
# Load training dataset
df = pd.read_csv(TELCO_CUSTOMERS_TRAIN_PATH)
df.head(3)

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,2926-JEJJC,Female,0,No,No,8,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Bank transfer (automatic),20.20,140.95,No
1,6029-CSMJE,Male,0,No,No,17,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,25.65,440.20,No
2,7321-ZNSLA,Male,0,Yes,Yes,13,No,No phone service,DSL,Yes,...,No,Yes,No,No,Two year,No,Mailed check,40.55,590.35,No

In [10]:
# Prepare dataset with categorical columns only
df_categorical = df[list(CATEGORICAL_COLUMNS)].copy()
df_categorical.head(3)

,gender,partner,dependents,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method
0,Female,No,No,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Bank transfer (automatic)
1,Male,No,No,No,No phone service,DSL,No,No,No,No,No,No,Month-to-month,Yes,Mailed check
2,Male,Yes,Yes,No,No phone service,DSL,Yes,Yes,No,Yes,No,No,Two year,No,Mailed check

In [11]:
df_categorical.shape

(5634, 15)

## Encode categorical columns using OneHotEncoder

In [12]:
encoder = OneHotEncoder(
    drop='if_binary',
    handle_unknown='ignore',
)
encoder.fit(df_categorical)

OneHotEncoder(drop='if_binary', handle_unknown='ignore')

In [14]:
# Transform categorical DataFrame
encoded = encoder.transform(df_categorical)

In [16]:
# Create a DataFrame from encoded features
df_categorical_encoded = pd.DataFrame(
    encoded.toarray(),
    columns=encoder.get_feature_names_out(),
    index=df_categorical.index,
)
df_categorical_encoded.head(3)

,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,multiple_lines_No,multiple_lines_No phone service,multiple_lines_Yes,internet_service_DSL,internet_service_Fiber optic,internet_service_No,...,streaming_movies_No internet service,streaming_movies_Yes,contract_Month-to-month,contract_One year,contract_Two year,paperless_billing_Yes,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check
0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [18]:
df_categorical_encoded.shape

(5634, 36)